var genTitle = function () {
    var pickedVals = [];
    var output = "";
    var sp = " ";
    var if1Ar = ["Een", "Deze"];
    var num = Math.ceil(Math.random() * 50);

    if (num === 1 || num >= 25) {
        num = rand(if1Ar);
    }

    for (var i = 0; i < texts.length; i++) {
        pickedVals.push(rand(texts[i]));
    }

    if (num === "A" && pickedVals[0].substring(0, 1).match(/[aeiouAEIOU]/)) {
        num = "An";
    }

    output += num + sp;
    for (var i = 0; i < pickedVals.length; i++) {
        output += sp + pickedVals[i];
        if ((num >= 1 && num <= 25) && i === 0) {
            output += "en ";
        }
        if (i === 2) {
            output += ". ";
        }
    }
    outputText(output);
}


var outputText = function (out) {
    document.getElementById("title-display").innerHTML = out;
}

var rand = function (ar) {
    return ar[Math.floor(Math.random() * ar.length)];
}

var texts = [
    [
        "man",
        "leerkracht",
        "vrouw",
        "leerling",
        "hond",
        "politicus",
        "fotograaf",
        "dief",
        "blik",
        "kind",
        "Gert Verhulst",
        "Marc Van Ranst",
        "viroloog",
        "politie",
        "koning",
        "influencer",
        "moeder",
        "vader",
        "demostrant",
        "communist",
        "fascist",
        "kunstenaar",
        "wetenschapper",
        "Sam",
        "Kim Jong Un",
        "Donald Trump",
        "Dries Van Langenhoven",
        "Kristof Calvo",
        "Groen",
        "Vlaams Belang",
        "PVDA",
        "Alcoholist",
        "blikje Cara pils",
        "oude man",
        "printer zonder inkt",
        "idioot",
        "psychopaat",
        "dokter",
        "viroloog",
        "The Beatles",
        "Aap",
        "Obama",
        "Konrad Maquestieau",
        "Marc Tops",
        "Peter Coen",
        "De Kunsthumaniora",
        "hond",
        "Verwarde man",
        "Vlaming",
        "God",
        "Allah",
        "Antifa",
        "relschopper"

    ], [

        "Plaste op",
        "sloeg",
        "at",
        "zat op",
        "liep op",
        "sprak met",
        "probeerde te knoeien met",
        "gevochten met",
        "geëlektrocuteerd",
        "gegeten",
        "gooide",
        "doode",
        "bevingerde",
        "wreef",
        "kuste",
        "sprong over",
        "schreeuwde tegen",
        "faalde",
        "kuste",
        "rookte een joint met",
        "verkocht drugs aan",
        "beweerde",
        "trouwde",
        "scheidde",
        "stal",
        "vochten over",
        "werd boos op",
        "werd bevriend met",
        "probeerde zelfmoord",
        "getunneld onder",
        "opende een blikje",
        "staarde naar",
        "weende",
        "sloeg",
        "dronk",
        "werd geslagen door",
        "ruinineerde",
        "werd neergeschoten",
        "ging op een date met",
        "probeerde te vluchten",
        "had een kind met",
        "werd ontvoerd door",
        "kocht",
        "werd burgermeester",
        "probeerde te begrijpen",
        "kon het niet begrijpen",
        "kon het niet aan",
        "zag",
        "een kopie gemaakt van",
        "deed een aanslag op",
        "dronk zich coma",
        "werd aangeklaagd door",
        "klaagde aan",
        "werd verliefd op",
        "tekende",
        "werd seksueel aangerand"


    ], [

        "een eend",
        "een naakte Bart Peeters",
        "een vliegende migrant",
        "een dode Frans Bauer",
        "Jan",
        "de Paus",
        "een banaan",
        "de kleur blauw",
        "het corona vaccin",
        "de eerste corona patient",
        "een fabriek",
        "levende Michael Jackson",
        "Will Smith",
        "de Eifeltoren",
        "een dunne Magie de block",
        "7 vampieren",
        "mijn vriendin",
        "Escobar",
        "een oude cd",
        "een transgender",
        "blijheid",
        "een Nazi",
        "de media",
        "Facebook",
        "Tumblr",
        "een mooie naaktfoto",
        "propaganda",
        "een printer",
        "meerdere allochtonen",
        "Miley Cyrus",
        "een aankomende trein",
        "een auto zonder wielen",
        "bier",
        "een cafe",
        "mij",
        "Nutella",
        "Hitler",
        "Donald Trump",
        "Bernie Sanders",
        "een dunne Amerikaan",
        "God",
        "de Walen",
        "de Vlamingen",
        "Porno",
        "Een aap",
        "traangas",
        "een bokser",
        "Elvis Presley",
        "een andere vent",
        "een hond",
        "een paart",
        "een kleine plas",
        "vuur",
        "een gaslek",
        "een waterfles",
        "een oud zwaard",
        "de bende van nijvel",
        "Napoleon",
        "Smashmouth",
        "Shrek",
        "Het laatste nieuws",
        "Een verwarde man",
        "mijn zelfvertrouwen",
        "een metalen ritje",
        "depressie",
        "de beurs",
        "een pizza",
        "de economie",
        "een school",
        "een kidnapper",
        "een egel",
        "een cult",
        "een zak pijnstillers",
        "Minecraft",
        "een gucci mondmasker",
        "[CENSORED]",
        "een gameboy",
        "een acteur uit Familie",
        "VTM nieuws",
        "het Journaal",
        "Koningin Elizabeth II",
        "een ijsje",
        "een luie Vlaming",
        "een werkende Waal",
        "een migrant",
        "Frank Verlie",
        "een UFO",
        "dubstep",
        "racisme",
        "een arbeider",
        "een kleuter"

    ], [

        "U zal nooit geloven wat erna gebuerde!",
        "Het werkte probleemloos!",
        "Wat er nu gebeurd zal je brein breken!",
        "Haal je portemonee al maar boven voor deze!",
        "Probeer er niet aan te denken...",
        "Wat een verspilling...",
        "Je zal nooit geloven wat het resultaat is!",
        "Geef me al je geld!",
        "ZWIJG EN NEEM MIJN GELD!!!",
        "Klik hier om meer te weten te komen!",
        "Vertel dit maar niet aan je echtgenoot.",
        "Zet je schrap!",
        "Praat over een moeilijke tijd...",
        "Kan ik een halelujah krijgen!?!?!",
        "Is dit het einde van democratie zoals we die kennen?",
        "Ik durf te wedden dat je dom genoeg bent hier op te klikken!",
        "Waarschuw je grootmoeder maar!",
        "Wat had je dan verwacht?",
        "Echt waar? kom op nou...",
        "Verhaal van mijn leven...",
        "Ze zijn zeker niet de slimste...",
        "Wat de f***!!",
        "Triggered.",
        "Ze kunnen maar beter een goede advocaat hebben...",
        "Ze hebben teminste een goede persoonlijkheid...",
        "Het ging best goed.",
        "Alsofg het verteld moet worden...",
        "ik geef op...",
        "Wie liet ze binnen???",
        "Wat.",
        "Feestje!",
        "je zal hierdoor niet kunnen slapen.",
        "Je zal dit nooit kunnen onzien!",
        "De stilte is oorverdovend...",
        "Bitch, please...",
        "Ik zou een boot moeten kopen...",
        "Mijn excuses hoor...",
        "#BlackLivesMatter",
        "Wie had het ooit kunnen raden!!!!!",
        "***WARNING*** deze link is NSFW!!!",
        "Tijd om een nieuwe baan te vinden...",
        "Praat over geluk!",
        "Make America Great Again!",
        "En ze vragen zich af waarom ze arm zijn...",
        "Oepsss...",
        "Ik ben er klaar met deze shit.",
        "Ik,ik kan niet meer...",
        "#Blessed",
        "Tuurlijk komt het door de sossen"
    ]];